name: winesapOS image build with stable repository and Arch Linux
on:
  push:
    branches:
      - stable
  workflow_dispatch:
jobs:
  build:
    name: System image build
    runs-on: ubuntu-24.04
    steps:
      - name: Maximize build space
        uses: smallprogram/maximize-build-space@master
        with:
            root-reserve-mb: 12288
            swap-size-mb: 2048
            remove-dotnet: 'true'
            remove-android: 'true'
            remove-haskell: 'true'
            remove-codeql: 'true'
            remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Install Bash
        run: sudo apt-get update && sudo apt-get install -y bash shellcheck
      - name: Check syntax of scripts
        run: |
          for i in $(find . -name "*.sh" | sort)
              do echo "${i}"
              if ! bash -n "${i}"; then
                  exit 1
              fi
              if ! shellcheck "${i}"; then
                  exit 1
              fi
          done
      - name: Obtain base docker image
        run: docker pull archlinux:latest
      - name: Create docker build image
        run: docker build --pull --no-cache -t winesapos-img-builder build/.
      - name: Build system image
        id: build_image
        run: docker run --rm -v $(pwd):/workdir -v /dev:/dev --env WINESAPOS_DEBUG_INSTALL=true --env WINESAPOS_DEBUG_TESTS=true --env WINESAPOS_ENABLE_PORTABLE_STORAGE=false --env WINESAPOS_TEST_VENTOY=false --env WINESAPOS_ENABLE_REPO_ROLLING=false --privileged=true winesapos-img-builder:latest /bin/bash -x /workdir/scripts/winesapos-build.sh
